Add SQLite backend
jimpil/duratom pull request #22
Opened 2022-05-07 02:44 UTC by wildwestrom

2022-05-07 10:11 UTC, jimpil requested changes

2022-05-07 10:11 UTC, jimpil commented on test/duratom/core_test.clj
> +    (.delete (io/file subname))))
prefer `io/delete-file` similar to line 290

2022-05-07 10:11 UTC, jimpil commented on src/clojure/duratom/utils.clj
> -(defn get-pgsql-value [db table-name row-id read-it!]
revert this renaming, and simply add the following:
```clj
(def get-sqlite-value get-pgsql-value)
```

2022-05-07 10:12 UTC, jimpil commented on src/clojure/duratom/core.clj
> +             rw default-postgres-rw}}]
use `default-sqlite-rw`

2022-05-07 10:12 UTC, jimpil commented on src/clojure/duratom/core.clj
> +             rw default-postgres-rw}}]
and here

2022-05-14 16:53 UTC, jimpil commented
Hi @wildwestrom, everything ok here? it's been a week since you opened this PR, and I've not heard back since...do you require any help addressing my comments?

2022-05-15 14:43 UTC, wildwestrom commented
My bad, just haven't gotten to it yet.

2022-05-16 07:20 UTC, wildwestrom commented
Ok, that should be good.

2022-05-17 22:10 UTC, jimpil requested changes
Ok, looks good - just one little thing (which  seems to have happened by accident).

2022-05-17 22:10 UTC, jimpil commented on src/clojure/duratom/core.clj
> +             rw default-sqlite-rw}}]
i think should be reverted  - this is `postgres-db` duragent

2022-05-20 20:29 UTC, jimpil approved these changes
Great stuff! Thanks for this...You can expect a new release by the end of the weekend 👍

2022-05-20 20:29 UTC, merged

2022-05-20 20:53 UTC, jimpil commented
FYI, `duratom 0.5.4` is up on clojars 🚀